from .f_SecondaryQrCodeLoginPermitNoticeService import Client as FSecondaryQrCodeLoginPermitNoticeServiceClient
from .f_SecondaryQrCodeLoginPermitNoticeService import Iface as FSecondaryQrCodeLoginPermitNoticeServiceIface
from .f_SecondaryQrCodeLoginPermitService import Client as FSecondaryQrCodeLoginPermitServiceClient
from .f_SecondaryQrCodeLoginPermitService import Iface as FSecondaryQrCodeLoginPermitServiceIface
from .f_SecondaryQrcodeLoginService import Client as FSecondaryQrcodeLoginServiceClient
from .f_SecondaryQrcodeLoginService import Iface as FSecondaryQrcodeLoginServiceIface
from .ttypes import *
