from .f_SecondaryQrCodeLoginPermitNoticeService import Client as FSecondaryQrCodeLoginPermitNoticeServiceClient
from .f_SecondaryQrCodeLoginPermitNoticeService import Iface as FSecondaryQrCodeLoginPermitNoticeServiceIface
from .f_SecondaryQrCodeLoginPermitService import Client as FSecondaryQrCodeLoginPermitServiceClient
from .f_SecondaryQrCodeLoginPermitService import Iface as FSecondaryQrCodeLoginPermitServiceIface
from .f_SecondaryQrCodeLoginService import Client as FSecondaryQrCodeLoginServiceClient
from .f_SecondaryQrCodeLoginService import Iface as FSecondaryQrCodeLoginServiceIface
from .ttypes import *
